### ISSUE TITLE
Browser vs Node detection in @itly/sdk unreliable with Webpack 5

### ISSUE THREAD

**Issue by alexkrolick** [amplitude/itly-sdk#111]
Webpack 5 removed the automatic polyfilling of Node globals like `process` in browser builds. However, it is common for users to add set the value of process.env.NODE_ENV and other variables using Webpack's DefinePlugin. This means that the lines below fail to detect the browser correctly and instead load the `node.ts` file, which is not compatible with the browser SDK. What was happening before was that it wasn't the `typeof process === 'undefined'`, `!p` check was causing the isBrowser boolean to be `true`, it was `p.browser === true` which is set by the [polyfill](https://github.com/defunctzombie/node-process/blob/master/browser.js#L156) (since removed).

https://github.com/amplitude/itly-sdk/blob/e7fab4c1ee0986bdc6bb6416de16a107da4254f2/packages/sdk/lib/index.ts#L43-L55

https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

Possible solutions:
1. Set the `browser` field in package.json for the SDK to `dist/browser.js` so that bundlers like Webpack and Browserify know to use that instead of index.js. This would avoid feature detection altogether.
2. Use a more reliable way of detecting that the script is in a browser environment, such as checking for the `window` or `document`.

Workarounds for users:
1. Add the polyfill: https://github.com/Richienb/node-polyfill-webpack-plugin
2. Use DefinePlugin to set `'process.browser': true` in addition to `process.env` or anything else you might be defining.

**Comment by justin-fiedler** [comment]
@alexkrolick Thanks for bringing this to our attention and even more for the potential solutions.

I will discuss with the team and try to get a fix out soon.

**Comment by justin-fiedler** [comment]
Hi @alexkrolick we just released version `2.3.4` in alpha which should resolve the issue. You can test using `yarn add @itly/sdk@alpha @itly/plugin-schema-validator@alpha` to update. Hope this fixes the problem for you.
